routes/web.php
<?php
use App\User;
use App\Notifications\TaskCompleteNotification;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	
    return view('welcome');
});
Route::get('/admin', function () {
	echo "string";
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
 Route::resource('company', 'CompanyController');
  Route::resource('notification', 'NotificationController');

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Company extends Model
{
   use SoftDeletes;
    protected $guarded=['id'];
    protected $fillable = [
        'name',
        'address'
    ];
}

app/Notification.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Notification extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use Auth;
use Illuminate\Http\Request;
use App\User;
use App\Notifications\TaskCompleteNotification;
use App\Notifications\SimpleNotification;
class CompanyController extends Controller
{
     public function __construct()
    {
        $this->middleware('auth');
    }

     private $view_root = 'modules/company/';
    public function index()

    {
       
       $users=Company::all();
       $view = view($this->view_root . 'index');
        $view->with('users', $users);
        return $view;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $request->validate([
            'name' => 'required|unique:companies',
            'address' => 'required'
        ]);
        $company = new Company;
        $company->fill($request->all());
        $company->creator_user_id = Auth::id();
        $company->active =true;
        $company->save();
         \App\User::find(1)->notify(
                        new SimpleNotification([
                            'subject'=>'Testing',
                            'sender_id'=>1,
                            'url'=>config('app.url').'/laravel_test/public/company',
                            'message'=>"For Today Delivery Quantity purpose"
                        ])
                    );
         $users=User::find(1);
         $users->notify(new TaskCompleteNotification);
         // Notification::send($users, new TaskCompleteNotification);


        return redirect()->route('company.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(company $company)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(company $company)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, company $company)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\company  $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(company $company)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/NotificationController.php
<?php

namespace App\Http\Controllers;

use App\Notification;
use Illuminate\Http\Request;

class NotificationController extends Controller
{
     private $view_root = 'modules/notification/';
    public function index()
    {
        
            $notifications=\Auth::user()->unreadNotifications;
            //'notifications'=>\Auth::user()->notifications
       

        //dd($data);

       
        $view = view($this->view_root . 'index');
        $view->with('notifications', $notifications);
        return $view;
    }

   
    public function create()
    {
        //
    }

  
    public function store(Request $request)
    {
        //
    }

    
    public function show(\App\Notification $notification)
    {
        $data=json_decode($notification->data);

        if(filter_var($data->url, FILTER_VALIDATE_URL) === FALSE){
            return redirect()->route('notification.index');
        }

        $notification->read_at=\Carbon\Carbon::now();
        $notification->save();

        return redirect()->away($data->url);
    }

    
    public function edit(Notification $notification)
    {
        //
    }

    
    public function update(Request $request, Notification $notification)
    {
        //
    }

   
   public function destroy(\App\Notification $notification){

        $notification->read_at=\Carbon\Carbon::now();
        $notification->save();
        return back();
        
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">Users</div>

                <div class="card-body">
                
                  <!--  -->
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                @if (Route::has('register'))
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                @endif
                            </li>
                        @else

                        <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                  Menus <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('company.index') }}" >
                                        {{ __('Company') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                            <li class="nav-item dropdown">

                                <a id="navbarDropdown1" class="nav-link" href="#" data-toggle="dropdown">
                                           Notify
                                         
                                             @if(\Auth::user()->unreadNotifications()->exists())
      
                <span style="color: red" class="badge">({{ \Auth::user()->unreadNotifications->count() }})</span>
            @endif
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown1">



                                       @if(\Auth::user()->unreadNotifications()->exists())
              @foreach(\Auth::user()->unreadNotifications as $row)
                
                  <a href="{{ route('notification.show', ['notification'=>$row->id]) }}">
                   
                    <span>
                      <span>Sender: {{ \App\User::find($row->data['sender_id'])->name }}</span><br>
                      <span class="time">{{ \Carbon\Carbon::parse($row->created_at)->diffForHumans() }}</span>
                    </span><br>
                    <span class="message">
                      <strong>{{ $row->data['subject'] }}:</strong> {{ $row->data['message'] }}
                    </span>
                  </a><br>
             
              @endforeach

            
                  <a href="{{ route('notification.index') }}">
                    <strong>See All Notifications</strong>
                    <i class="fa fa-angle-right"></i>
                  </a>
              

            @else
       
                  <a>
                    <strong>Does't have any unread notification.</strong>
                  </a>
               

            @endif
                                

                                   
                                </div>
                            </li>

                             <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/modules/company/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">Company Create</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('company.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('Address') }}</label>

                            <div class="col-md-6">
                                <input id="address" type="text" class="form-control{{ $errors->has('address') ? ' is-invalid' : '' }}" name="address" value="{{ old('address') }}" required>

                                @if ($errors->has('address'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('address') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                          <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Save') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">Companies</div>

                <div class="card-body">
                     <table class="table table-striped">
                        <thead>
                          <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Address</th>
                          </tr>
                        </thead>
                        <tbody>
                          @foreach($users as $user)
                              <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td> {{ $user->name }}</td>
                                <td> {{ $user->address }}</td>
                              </tr>   
                           @endforeach 
                          
                        </tbody>
                      </table>
                 
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/modules/notification/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Notification</div>

                <div class="card-body">
                    <div class="table-responsive">
                            <table id="datatable-buttons" class="table table-bordered table-hover">
                                <thead class="bg-primary">
                                    <tr>
                                        <th width="25">#</th>
                                        <th>Time</th>
                                        <th>Sender</th>
                                        <th>Subject</th>
                                        <th>Message</th>
                                        <th>Detail</th>
                                        <th>Mark As Read</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($notifications as $row)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ \Carbon\Carbon::parse($row->created_at)->diffForHumans() }}</td>
                                        <td>{{ \App\User::find($row->data['sender_id'])->name }}</td>
                                        <td>{{ $row->data['subject'] }}</td>
                                        <td>{{ $row->data['message'] }}</td>
                                        <td>
                                             <a href="{{route('notification.show', ['notification'=>$row->id])}}" class="btn btn-info" role="button">View Details</a>
                                        </td>
                                        <td>
                                            @if(!$row->read_at)
                                            <a href="{{route('notification.destroy', ['notification'=>$row->id])}}" class="btn btn-info" role="button">Mark As Read</a>
                                            @endif

                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                 
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

 